// styles
import "../styles/globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

// components
import Header from "@/components/shared/header-footer/Header/Header";

const inter = Inter({
  weight: ["400", "700"],
  style: "normal",
  display: "swap",
  variable: "--font-inter",
  subsets: ["latin"],
});

import { cn } from "./utils/cn";
import Footer from "@/components/shared/header-footer/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Params = Promise<{ slug: string }>;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
  params: Params;
}>) {
  return (
    <html lang="ru">
      <body className={cn(`${inter.variable} antialiased`)}>
        <div className="grid h-screen grid-rows-[auto_1fr_auto]">
          <Header />
          <main className="mx-auto w-full max-w-screen-3xl">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
